[build]
  publish = "dist/public"
  command = "npm run build"

# Proxy /api calls to the backend server
[[redirects]]
  from = "/api/*"
  to = "https://ais-dev-fla4gi37b6w6gqko6ziase-45369408487.asia-southeast1.run.app/api/:splat"
  status = 200
  force = true

# Single Page Application (SPA) catch-all routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
